### ISSUE TITLE
[Off-Topic] can you please help me?

### ISSUE THREAD

**Issue by Nishant1500** [dekts/live-stream#1]
Hello There!
I am Nishant. Can you help me please? I am stuck with this question that how to add a Xbox Scope In Azure AD OAuth.i didn't find any scopes in the API Permission Tab. Then I saw Ur comment so did u find any ways?
This is the comment I Found
![20210518_211907](https://user-images.githubusercontent.com/53296643/118683139-c0e9a780-b81e-11eb-8602-eacc1046378b.jpg)

**Comment by dekts** [comment]
Hey Nishant

For Xbox, you have to create an app on the Azure platform and then grant the necessary permissions to it. If everything goes according to plan, you can then use that created app and execute your great plan.

**Comment by Nishant1500** [comment]
Yeah I created thr Azure AD application but I am unable to find the Xbox Live Scope/Permission

**Comment by Nishant1500** [comment]
Hello There!
I have answered https://stackoverflow.com/q/63898540/13772946

Hope That Helps You

Best,
Nish

**Comment by dekts** [comment]
Several months ago I already figured out how to utilize it and the feature is working as expected. As soon as I get a good time, I will post the correct solution.

**Comment by Nishant1500** [comment]
# 👍
